import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-100 flex items-center justify-center min-h-screen p-4">
        <div className="iphone-frame relative bg-black rounded-[50px] w-[375px] h-[812px] p-[12px] shadow-xl">
          <div className="iphone-screen bg-white rounded-[40px] w-full h-full overflow-hidden">
            <div className="iphone-content h-full overflow-y-auto">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
